/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "or_gate.v:1" *)
module or_gate(a, b, y);
  (* src = "or_gate.v:4" *)
  input a;
  (* src = "or_gate.v:5" *)
  input b;
  (* src = "or_gate.v:6" *)
  output y;
  assign y = b | a;
endmodule
